### ISSUE TITLE
分辨率适配

### ISSUE THREAD

**Issue by wgnyjn** [Spr-Aachen/Genshin-to-Honkai-PC-Control-Modification-Project#1]
大佬好，请问下能不能适配2560*1080的分辨率呀

**Comment by Spr-Aachen** [comment]
应该是可以的哦，但是需要你协助提供相应分辨率的录屏素材。

需要录制战斗界面和乐土大厅界面，
且战斗界面需要将低血量的状态录进去，因为低血量时会有色差变动。

游戏内需要设置如下：
1.使用键鼠
2.关闭菜单提示
3.开启按键提示和关闭按键提示的情况各录制一次
4.图像对比度保持默认，不开柔光

录制的比特率尽量保持在45000以上，因为像素点要足够清晰

**Comment by wgnyjn** [comment]
好的大佬，我等下去试试

**Comment by wgnyjn** [comment]
大佬能留个邮箱吗，等会录好给您发过去

**Comment by wgnyjn** [comment]
大佬，请问下是不是进乐土大厅和战斗界面站着就可以呀？
然后大佬能不能留一个邮箱呀？等会录好就发过去

**Comment by Spr-Aachen** [comment]
是的，站着不动就好了，战斗界面的话尽量选择万象虚境或后崩场景因为UI辨识度高一些

我的邮箱：2835946988@qq.com

**Comment by wgnyjn** [comment]
好的，晚上回去我把这几个场景都录上一遍。
（顺便一提，大佬视频已三连）

**Comment by Spr-Aachen** [comment]
哇，谢谢！

**Comment by wgnyjn** [comment]
不客气啦，我还要感谢大佬开发出这么厉害的软件呢
对了大佬，我已经把录屏发给你啦，你看看还需要其他的了吗
